### ISSUE TITLE
如何在样本中增加负样本？

### ISSUE THREAD

**Issue by lyp-deeplearning** [biubug6/Face-Detector-1MB-with-landmark#14]
感谢您这么棒的工作，我想请教下您提供的widerface训练集的标签里面很多样本label被设置为-1，这是把那些小脸或者模糊的脸直接作为负样本吗？
       如果我想减少模型对于一些场景的误识别，也认为把一些容易识别错误的目标设为-1，这样在计算loss的时候负样本的选取会优先考虑这部分标注过的负样本吗。
       但是在看multibox_loss函数的时候好像还是把所有的负样本按照loss的排序排序选取前面一部分，这样的话如果与我标记的负样本匹配的defaultbox的loss不是排在前面，它还是会被筛选掉。

**Comment by biubug6** [comment]
label为-1 仅仅是因为一些人脸无法标注关键点信息, 只是用来回归位置信息(不回归关键点信息)

**Comment by lyp-deeplearning** [comment]
@biubug6 好的，谢谢解答！

**Comment by watertianyi** [comment]
@biubug6 你好，我想知道 wider_val.txt这个验证集怎么获取，你发的链接失效了，可以再发一遍吗，而且为什么是没有人脸框与landmark的文件，retinaFace标注的文件好像也只有
