### ISSUE TITLE
onnx模型验证

### ISSUE THREAD

**Issue by yjhuasheng** [biubug6/Face-Detector-1MB-with-landmark#15]
您好，我想请问一下，转成onnx后，如何验证转成onnx模型的精度？有demo可以参考吗？

**Comment by onnx20** [comment]
> 您好，我想请问一下，转成onnx后，如何验证转成onnx模型的精度？有demo可以参考吗？

可以使用onnxruntime模块，微软出品的，部分参考代码：

import onnxruntime as ort
model_onnx = ort.InferenceSession('FaceDetector.onnx')
input_name = model_onnx.get_inputs()[0].name
output_names = [output.name for output in model_onnx.get_outputs()]
outputs = model_onnx.run(output_names,{input_name: input.numpy()})

**Comment by Single430** [comment]
@yjhuasheng  你好，onnx模型验证可以分享下代码吗？

**Comment by yjhuasheng** [comment]
> @yjhuasheng 你好，onnx模型验证可以分享下代码吗？

这个我也没有验证，只是在自己工程上测试一下转过的模型结果，0.0
