### ISSUE TITLE
您好，感谢你提供的代码，请可以在提供一份mobilenetX0.25的在image上面的预训练模型吗

### ISSUE THREAD

**Issue by LLLLLLoki** [biubug6/Face-Detector-1MB-with-landmark#30]
./weights/mobilenetV1X0.25_pretrain.tar  兄弟 ，这个文件我没找到下载地方

**Comment by goldlee** [comment]
@LLLLLLoki 老哥，这里可以下载https://drive.google.com/drive/folders/1oZRSG0ZegbVkVwUd8wUIQx8W7yfZ_ki1

**Comment by LLLLLLoki** [comment]
兄弟 谢谢啦
