### ISSUE TITLE
onnx2ncnn的问题

### ISSUE THREAD

**Issue by Vivianyzw** [biubug6/Face-Detector-1MB-with-landmark#31]
在执行./onnx2ncnn face.param face.bin时报错：
./onnx2ncnn: error while loading shared libraries: libprotobuf.so.20: cannot open shared object file: No such file or directory
请问该如何解决？
有尝试过https://github.com/onnx/onnx/issues/2434 中的conda install protobuf=3.9，但是无效

**Comment by dianxin556** [comment]
同问

**Comment by Vivianyzw** [comment]
这个自己重新编译一个ncnn工具就可以了

**Comment by dianxin556** [comment]
@Vivianyzw ,多谢，已解决。

**Comment by xxxpsyduck** [comment]
@Vivianyzw Can you give more detail?

**Comment by llf10811020205** [comment]
> @Vivianyzw ,多谢，已解决。
您好， 能讲下怎么解决的吗？

**Comment by rosaline1995** [comment]
> > @Vivianyzw ,多谢，已解决。
> > 您好， 能讲下怎么解决的吗？

在这里https://github.com/Tencent/ncnn 安装编译然后找到onnx2ncnn即可。

**Comment by littlerookie6990** [comment]
> 这个自己重新编译一个ncnn工具就可以了

我是编译好的，但是出现错误
