### ISSUE TITLE
关于多分类

### ISSUE THREAD

**Issue by duorouputao** [biubug6/Face-Detector-1MB-with-landmark#32]
您好，我在处理多分类时，也就是num_classes = 3，在塞数据的地方annotation[0, 14]的地方多了一个label,也就是标签有-1，1，2，但是这样子训练之后网络并不能较好地区分处理，结果是算法推理的结果基本都偏向于标签为1，请问下有什么比较好的解决方法吗~ 麻烦您指教下~感激不尽

**Comment by stevenluzheng123456** [comment]
我也有相同的问题，你最后怎么解决的？
