### ISSUE TITLE
Questions aboult weights

### ISSUE THREAD

**Issue by wqvbjhc** [biubug6/Face-Detector-1MB-with-landmark#5]
there are three files in weights dir:
_mobilenet0.25_Final.pth
RBF_Final.pth
slim_Final.pth_
the "convert_to_onnx.py" user long_side param to Specifies the w&h. 
but i found the w&h are the same, on Ultra-Light-Fast-Generic-Face-Detector-1MB, the author has two pretrain weight: 320*240 and 640*480. 
Did you use different resolution to train the network?
What resolution is the model on  weights dir trained with?yk
Is the same weight use to test the  wider face val of different resolution(320*240 640*480), only resize input image to different resolution?

**Comment by biubug6** [comment]
I use random crop and scale to 300*300 of proportion when training.  Ultra-Light-Fast-Generic-Face-Detector-1MB scale to 320*240 of no proportion. 
When testing ,  using the same weight and scale long side to 320 or 640 of proportion.

**Comment by wqvbjhc** [comment]
@biubug6 thx
