### ISSUE TITLE
Vertical screen big face easy to get wrong face location

### ISSUE THREAD

**Issue by wqvbjhc** [biubug6/Face-Detector-1MB-with-landmark#6]
src image
![1person_2](https://user-images.githubusercontent.com/931518/67942776-953ea680-fc13-11e9-9715-a7a613c02d6b.jpg)

result img
![test](https://user-images.githubusercontent.com/931518/67942784-9a035a80-fc13-11e9-9003-bef6f3c52a6a.jpg)

why?

the command as follow:
python detect.py --network mobile0.25 --trained_model ./weights/mobilenet0.25_Final.pth
or
python detect.py --network RFB --trained_model ./weights/RBF_Final.pth
or 
python detect.py --network slim --trained_model ./weights/slim_Final.pth
are the same wrong result.

**Comment by biubug6** [comment]
Because of small anchor size, it is hard to detect large face(such as face larger than 512). You can scale long side of image to 640 or 320 to get a better result which also gets a faster speed.

**Comment by wqvbjhc** [comment]
in the detect.py, the long_side default is 640. so it had scale long side of image to 640.

**Comment by biubug6** [comment]
You should change origin_size to False in "parser.add_argument('--origin_size', default=True, type=str, help='Whether use origin image size to evaluate') ".

**Comment by wqvbjhc** [comment]
@biubug6 got it. when origin_size=false and long_sid=640. it's good to detect only one face.
